version: "3.6"
services:
  mysql:
    container_name: kotlin_elastic_mysql
    build: mysql
    ports:
      - "3309:3306"
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d # For Database initialize
    environment:
      MYSQL_DATABASE: kotlin_elastic_db
      MYSQL_USER: kotlin_elastic_user
      MYSQL_PASSWORD: password
  sqs:
    container_name: kotlin_elastic_sqs
    build: sqs
    ports:
      - "9324:9324"
  elasticsearch:
    container_name: kotlin_elastic_es
    build: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"