/*
 * This file is generated by jOOQ.
 */
package jooq.kotlin_elastic_db;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import jooq.DefaultCatalog;
import jooq.kotlin_elastic_db.tables.Users;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KotlinElasticDb extends SchemaImpl {

    private static final long serialVersionUID = -1570080928;

    /**
     * The reference instance of <code>kotlin_elastic_db</code>
     */
    public static final KotlinElasticDb KOTLIN_ELASTIC_DB = new KotlinElasticDb();

    /**
     * The table <code>kotlin_elastic_db.users</code>.
     */
    public final Users USERS = jooq.kotlin_elastic_db.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private KotlinElasticDb() {
        super("kotlin_elastic_db", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Users.USERS);
    }
}
