/*
 * This file is generated by jOOQ.
 */
package jooq.kotlin_elastic_db;


import javax.annotation.Generated;

import jooq.kotlin_elastic_db.tables.Users;


/**
 * Convenience access to all tables in kotlin_elastic_db
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>kotlin_elastic_db.users</code>.
     */
    public static final Users USERS = jooq.kotlin_elastic_db.tables.Users.USERS;
}
